"""Changed edges table from primary constraint to unique constraint

Revision ID: 44b0abd53d7b
Revises: 98d05bedf779
Create Date: 2024-12-08 15:17:22.169821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b0abd53d7b'
down_revision = '98d05bedf779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['source', 'target'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
